export { default as Home } from './MainPage/Home';
export { default as LoginPage } from './LoginPage/LoginPage';
export { default as RegistrationPage } from './RegistrationPage/RegistrationPage';
export { default as Store } from './Store/Store';
export { default as AboutPage } from './AboutPage/About';
export { default as NotFound } from './NotFoundPage/NotFound';
export { default as ProfilePage } from './ProfilePage/ProfilePage';
export { default as CartPage } from './CartPage/CartPage';
export { default as ProductDetail } from './ProductPage/ProductPage';
